apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotenberg-deployment
  labels:
    app: api-gotenberg
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gotenberg
  template:
    metadata:
      labels:
        app: api-gotenberg
    spec:
      containers:
        - name: gotenberg
          image: evodimregistry.azurecr.io/gotenberg:6
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-gotenberg
spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    app: api-gotenberg
